# Generated by Django 5.0.6 on 2024-06-29 07:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SKU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest_app.category')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest_app.department')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest_app.location')),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest_app.subcategory')),
            ],
        ),
    ]
